{"uuid": "6ccd77a5-b0b9-46d8-929c-afef0072506b", "children": ["8b6a423c-3d1b-4326-b49b-6de741b75430", "a3a7fa12-893d-4f3e-b5d9-fa7f7dfc02cc"], "befores": [{"name": "beforeclass", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000133380C9E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\Appium_Framework\\test\\conftest.py\", line 11, in beforeclass\n    driver = driver1.getdrivermethod()\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\Appium_Framework\\base\\driverClass.py\", line 15, in getdrivermethod\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", desired_caps)\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 274, in __init__\n    super().__init__(\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 269, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 369, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 423, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 333, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 355, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 785, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\user\\PycharmProjects\\Appium_project\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1653540355155, "stop": 1653540363337}], "start": 1653540355155, "stop": 1653540365021}